FROM openjdk
WORKDIR usr/lib
ADD ./target/BEJ-C3-S1-SpringBoot-MC-User-0.0.1-SNAPSHOT.jar /usr/lib/BEJ-C3-S1-SpringBoot-MC-User-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","BEJ-C3-S1-SpringBoot-MC-User-0.0.1-SNAPSHOT.jar"]